[package]
name = "pcloud-http-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcloud = { path = "../lib" }
#
actix-web = { version = "4.0.0-beta.8" }
env_logger = { version = "^0.9" }
human_bytes = { version = "^0.3", features = ["bibytes"] }
log = { version = "^0.4" }
