on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Docker builds

jobs:
  build-debian:
    name: building debian image
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: jdrouet/pcloud-http-server:debian-canary
          file: ./scripts/debian.Dockerfile

  build-alpine:
    name: building alpine image
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: jdrouet/pcloud-http-server:alpine-canary
          file: ./scripts/alpine.Dockerfile
