on: [push]

name: Continuous integration

jobs:
  check:
    name: Check and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install libfuse3-dev
        run: sudo apt-get install -y libfuse3-dev
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --tests
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  
  testing:
    name: Run all the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install libfuse3-dev
        run: sudo apt-get install -y libfuse3-dev
      - uses: actions-rs/cargo@v1
        env:
          PCLOUD_USERNAME: "${{secrets.PCLOUD_USERNAME}}"
          PCLOUD_PASSWORD: "${{secrets.PCLOUD_PASSWORD}}"
          PCLOUD_REGION: "${{secrets.PCLOUD_REGION}}"
        with:
          command: test
          args: --features protected
